/** LingoPro — Vocabulary Seed Data */
const words = [
  // Oxford 5000 · A1 · Daily Life
  { word:"ability", meaning_vn:"khả năng, năng lực", definition_vn:"Sức mạnh, kỹ năng để làm được việc gì đó.", definition_en:"The power or skill to do something.", example:"She has the ability to speak three languages.", level:"A1", source:"Oxford 5000", topic:"Daily Life", difficulty:1, frequency_rank:1200, tags:["basic","common"], partOfSpeech:"noun" },
  { word:"accept", meaning_vn:"chấp nhận, đồng ý", definition_vn:"Đồng ý nhận hoặc làm điều gì đó.", definition_en:"To agree to take or do something.", example:"Please accept my apologies.", level:"A1", source:"Oxford 5000", topic:"Daily Life", difficulty:1, frequency_rank:800, tags:["basic","common"], partOfSpeech:"verb" },
  { word:"achieve", meaning_vn:"đạt được, hoàn thành", definition_vn:"Thành công trong việc đạt được điều gì đó sau khi nỗ lực.", definition_en:"To successfully reach a goal through effort.", example:"She worked hard to achieve her dreams.", level:"A2", source:"Oxford 5000", topic:"Daily Life", difficulty:2, frequency_rank:950, tags:["common"], partOfSpeech:"verb" },
  { word:"activity", meaning_vn:"hoạt động", definition_vn:"Việc làm mà ai đó thực hiện để giải trí.", definition_en:"Something done as a hobby or for enjoyment.", example:"Swimming is a great outdoor activity.", level:"A1", source:"Oxford 5000", topic:"Daily Life", difficulty:1, frequency_rank:700, tags:["basic"], partOfSpeech:"noun" },
  { word:"advice", meaning_vn:"lời khuyên", definition_vn:"Ý kiến về việc bạn nên làm trong một tình huống.", definition_en:"An opinion about what someone should do.", example:"She gave me good advice about my career.", level:"A2", source:"Oxford 5000", topic:"Daily Life", difficulty:2, frequency_rank:1100, tags:["common"], partOfSpeech:"noun" },
  { word:"agree", meaning_vn:"đồng ý", definition_vn:"Có cùng quan điểm với ai đó.", definition_en:"To have the same opinion as someone.", example:"Do you agree with me on this?", level:"A1", source:"Oxford 5000", topic:"Daily Life", difficulty:1, frequency_rank:600, tags:["basic","common"], partOfSpeech:"verb" },
  { word:"amazing", meaning_vn:"tuyệt vời, kinh ngạc", definition_vn:"Rất ấn tượng hoặc đáng ngạc nhiên.", definition_en:"Very impressive or surprising.", example:"The view from the top was amazing.", level:"A1", source:"Oxford 5000", topic:"Daily Life", difficulty:1, frequency_rank:900, tags:["basic","adjective"], partOfSpeech:"adjective" },
  { word:"beautiful", meaning_vn:"đẹp, xinh đẹp", definition_vn:"Có vẻ đẹp rất dễ chịu.", definition_en:"Pleasing to the senses or mind.", example:"What a beautiful sunset!", level:"A1", source:"Oxford 3000", topic:"Daily Life", difficulty:1, frequency_rank:400, tags:["basic","adjective"], partOfSpeech:"adjective" },
  { word:"comfortable", meaning_vn:"thoải mái, tiện nghi", definition_vn:"Mang lại sự thoải mái về thể chất.", definition_en:"Providing physical ease and relaxation.", example:"This sofa is very comfortable.", level:"A1", source:"Oxford 3000", topic:"Daily Life", difficulty:1, frequency_rank:900, tags:["basic","adjective"], partOfSpeech:"adjective" },
  { word:"communicate", meaning_vn:"giao tiếp, truyền đạt", definition_vn:"Chia sẻ thông tin với người khác.", definition_en:"To share information with others.", example:"We communicate mainly by email.", level:"A2", source:"Oxford 3000", topic:"Daily Life", difficulty:2, frequency_rank:800, tags:["common","social"], partOfSpeech:"verb" },
  { word:"concentrate", meaning_vn:"tập trung", definition_vn:"Hướng sự chú ý vào một thứ cụ thể.", definition_en:"To direct attention to one thing.", example:"I can't concentrate with all that noise.", level:"A2", source:"Oxford 3000", topic:"Daily Life", difficulty:2, frequency_rank:1200, tags:["common","study"], partOfSpeech:"verb" },
  { word:"confident", meaning_vn:"tự tin", definition_vn:"Cảm thấy chắc chắn về khả năng của bản thân.", definition_en:"Feeling certain about one's own abilities.", example:"She felt confident before the interview.", level:"A2", source:"Oxford 3000", topic:"Daily Life", difficulty:2, frequency_rank:1100, tags:["common","adjective"], partOfSpeech:"adjective" },

  // Oxford 5000 · A2–B1 · Travel
  { word:"adventure", meaning_vn:"cuộc phiêu lưu", definition_vn:"Một trải nghiệm thú vị và hơi nguy hiểm.", definition_en:"An exciting and slightly dangerous experience.", example:"Backpacking through Asia was a real adventure.", level:"A2", source:"Oxford 5000", topic:"Travel", difficulty:2, frequency_rank:1500, tags:["travel"], partOfSpeech:"noun" },
  { word:"airport", meaning_vn:"sân bay", definition_vn:"Nơi máy bay cất cánh và hạ cánh.", definition_en:"A place where aircraft take off and land.", example:"We arrived at the airport two hours early.", level:"A1", source:"Oxford 5000", topic:"Travel", difficulty:1, frequency_rank:1100, tags:["travel","basic"], partOfSpeech:"noun" },
  { word:"baggage", meaning_vn:"hành lý", definition_vn:"Túi, vali mang theo khi đi du lịch.", definition_en:"Bags and suitcases taken on a trip.", example:"Please collect your baggage from carousel 3.", level:"A2", source:"Oxford 5000", topic:"Travel", difficulty:2, frequency_rank:2200, tags:["travel"], partOfSpeech:"noun" },
  { word:"destination", meaning_vn:"điểm đến", definition_vn:"Nơi mà ai đó đang đi đến.", definition_en:"The place someone is travelling to.", example:"Paris was our final destination.", level:"A2", source:"Oxford 5000", topic:"Travel", difficulty:2, frequency_rank:1800, tags:["travel"], partOfSpeech:"noun" },
  { word:"accommodation", meaning_vn:"chỗ ở", definition_vn:"Một nơi để ở khi đang đi du lịch.", definition_en:"A place to stay when travelling.", example:"The hotel accommodation was excellent.", level:"B1", source:"Oxford 5000", topic:"Travel", difficulty:3, frequency_rank:2000, tags:["travel"], partOfSpeech:"noun" },
  { word:"itinerary", meaning_vn:"lịch trình hành trình", definition_vn:"Kế hoạch chi tiết về một chuyến đi.", definition_en:"A detailed plan for a journey.", example:"The travel agent prepared a full itinerary.", level:"B2", source:"Oxford 5000", topic:"Travel", difficulty:4, frequency_rank:3500, tags:["travel","planning"], partOfSpeech:"noun" },
  { word:"customs", meaning_vn:"hải quan", definition_vn:"Cơ quan kiểm tra hàng hóa ra vào quốc gia.", definition_en:"The official process of checking goods entering a country.", example:"We had to declare our goods at customs.", level:"B1", source:"Oxford 5000", topic:"Travel", difficulty:3, frequency_rank:2800, tags:["travel"], partOfSpeech:"noun" },

  // Oxford 5000 · B1–B2 · Business
  { word:"budget", meaning_vn:"ngân sách", definition_vn:"Số tiền có thể chi tiêu cho một mục đích.", definition_en:"The amount of money available for a purpose.", example:"We need to stay within the project budget.", level:"B1", source:"Oxford 5000", topic:"Business", difficulty:3, frequency_rank:1400, tags:["business","finance"], partOfSpeech:"noun" },
  { word:"collaborate", meaning_vn:"hợp tác, cộng tác", definition_vn:"Làm việc cùng người khác để đạt mục tiêu.", definition_en:"To work with others to achieve something.", example:"We need to collaborate with the marketing team.", level:"B1", source:"Oxford 5000", topic:"Business", difficulty:3, frequency_rank:2100, tags:["business","teamwork"], partOfSpeech:"verb" },
  { word:"deadline", meaning_vn:"hạn chót", definition_vn:"Thời điểm mà công việc phải hoàn thành.", definition_en:"The latest time by which work must be done.", example:"The project deadline is Friday.", level:"B1", source:"Oxford 5000", topic:"Business", difficulty:3, frequency_rank:1900, tags:["business"], partOfSpeech:"noun" },
  { word:"efficient", meaning_vn:"hiệu quả", definition_vn:"Hoạt động tốt mà không lãng phí tài nguyên.", definition_en:"Working well without wasting resources.", example:"The new system is much more efficient.", level:"B1", source:"Oxford 5000", topic:"Business", difficulty:3, frequency_rank:1700, tags:["business"], partOfSpeech:"adjective" },
  { word:"negotiate", meaning_vn:"đàm phán, thương lượng", definition_vn:"Cố gắng đạt thỏa thuận qua thảo luận.", definition_en:"To try to reach an agreement through discussion.", example:"They negotiated a better salary package.", level:"B2", source:"Oxford 5000", topic:"Business", difficulty:4, frequency_rank:2000, tags:["business"], partOfSpeech:"verb" },
  { word:"revenue", meaning_vn:"doanh thu", definition_vn:"Thu nhập mà công ty kiếm được từ kinh doanh.", definition_en:"The income a business earns from its activities.", example:"The company's annual revenue grew by 15%.", level:"B2", source:"Oxford 5000", topic:"Business", difficulty:4, frequency_rank:2300, tags:["business","finance"], partOfSpeech:"noun" },
  { word:"strategy", meaning_vn:"chiến lược", definition_vn:"Kế hoạch được thiết kế để đạt mục tiêu dài hạn.", definition_en:"A plan designed to achieve a long-term goal.", example:"We need a new marketing strategy.", level:"B1", source:"Oxford 5000", topic:"Business", difficulty:3, frequency_rank:1600, tags:["business"], partOfSpeech:"noun" },

  // Oxford 3000 · A2–B1 · Food
  { word:"appetite", meaning_vn:"sự thèm ăn", definition_vn:"Cảm giác muốn ăn.", definition_en:"The feeling of wanting to eat food.", example:"Exercise always gives me a good appetite.", level:"B1", source:"Oxford 3000", topic:"Food", difficulty:3, frequency_rank:3000, tags:["food"], partOfSpeech:"noun" },
  { word:"cuisine", meaning_vn:"ẩm thực", definition_vn:"Phong cách nấu ăn đặc trưng của một quốc gia.", definition_en:"The style of cooking of a particular country.", example:"Thai cuisine is known for its bold flavors.", level:"B1", source:"Oxford 3000", topic:"Food", difficulty:3, frequency_rank:2700, tags:["food","culture"], partOfSpeech:"noun" },
  { word:"delicious", meaning_vn:"ngon, thơm ngon", definition_vn:"Có mùi vị rất ngon.", definition_en:"Having a very pleasant taste.", example:"This pasta is absolutely delicious!", level:"A1", source:"Oxford 3000", topic:"Food", difficulty:1, frequency_rank:1500, tags:["food","basic"], partOfSpeech:"adjective" },
  { word:"ingredient", meaning_vn:"nguyên liệu, thành phần", definition_vn:"Một trong những thứ dùng để làm thức ăn.", definition_en:"One of the things used to make a food.", example:"The main ingredient is fresh tomatoes.", level:"A2", source:"Oxford 3000", topic:"Food", difficulty:2, frequency_rank:2100, tags:["food","cooking"], partOfSpeech:"noun" },
  { word:"recipe", meaning_vn:"công thức nấu ăn", definition_vn:"Hướng dẫn cách chuẩn bị và nấu một món ăn.", definition_en:"Instructions for preparing and cooking food.", example:"Can you share your recipe for this cake?", level:"A2", source:"Oxford 3000", topic:"Food", difficulty:2, frequency_rank:2000, tags:["food","cooking"], partOfSpeech:"noun" },
  { word:"nutrition", meaning_vn:"dinh dưỡng", definition_vn:"Quá trình cung cấp thức ăn cần thiết cho sức khỏe.", definition_en:"The process of providing food necessary for health.", example:"Good nutrition is essential for children.", level:"B1", source:"Oxford 3000", topic:"Food", difficulty:3, frequency_rank:2400, tags:["food","health"], partOfSpeech:"noun" },
  { word:"flavor", meaning_vn:"hương vị, mùi vị", definition_vn:"Vị đặc trưng của thức ăn hay đồ uống.", definition_en:"The particular taste of food or drink.", example:"This soup has a rich, smoky flavor.", level:"A2", source:"Oxford 3000", topic:"Food", difficulty:2, frequency_rank:1800, tags:["food"], partOfSpeech:"noun" },

  // Cambridge B1/B2 · Technology
  { word:"algorithm", meaning_vn:"thuật toán", definition_vn:"Tập hợp các quy tắc để giải quyết vấn đề trong máy tính.", definition_en:"A set of rules for solving problems in computing.", example:"The search engine uses a complex algorithm.", level:"B2", source:"Cambridge B1/B2", topic:"Technology", difficulty:4, frequency_rank:3100, tags:["technology"], partOfSpeech:"noun" },
  { word:"application", meaning_vn:"ứng dụng, phần mềm", definition_vn:"Chương trình máy tính cho một nhiệm vụ cụ thể.", definition_en:"A computer program designed for a specific task.", example:"Download the application from the App Store.", level:"A2", source:"Cambridge B1/B2", topic:"Technology", difficulty:2, frequency_rank:800, tags:["technology","basic"], partOfSpeech:"noun" },
  { word:"database", meaning_vn:"cơ sở dữ liệu", definition_vn:"Tập hợp dữ liệu có tổ chức lưu trữ trong máy tính.", definition_en:"An organized collection of data stored on a computer.", example:"All customer records are in the database.", level:"B1", source:"Cambridge B1/B2", topic:"Technology", difficulty:3, frequency_rank:2200, tags:["technology"], partOfSpeech:"noun" },
  { word:"encryption", meaning_vn:"mã hóa", definition_vn:"Quá trình chuyển thông tin thành dạng bí mật.", definition_en:"The process of converting information into a secret form.", example:"End-to-end encryption protects your messages.", level:"B2", source:"Cambridge B1/B2", topic:"Technology", difficulty:5, frequency_rank:3800, tags:["technology","security"], partOfSpeech:"noun" },
  { word:"interface", meaning_vn:"giao diện", definition_vn:"Điểm tương tác giữa người dùng và phần mềm.", definition_en:"The point where user and software interact.", example:"The new user interface is much cleaner.", level:"B1", source:"Cambridge B1/B2", topic:"Technology", difficulty:3, frequency_rank:2400, tags:["technology","design"], partOfSpeech:"noun" },
  { word:"wireless", meaning_vn:"không dây", definition_vn:"Kết nối mà không cần dây.", definition_en:"Connecting without wires.", example:"The office has wireless internet access.", level:"A2", source:"Cambridge B1/B2", topic:"Technology", difficulty:2, frequency_rank:1900, tags:["technology"], partOfSpeech:"adjective" },
  { word:"automation", meaning_vn:"tự động hóa", definition_vn:"Dùng công nghệ thực hiện tác vụ không cần con người.", definition_en:"Using technology to perform tasks without human help.", example:"Automation is changing manufacturing.", level:"B2", source:"IELTS Core", topic:"Technology", difficulty:4, frequency_rank:3300, tags:["technology"], partOfSpeech:"noun" },
  { word:"innovation", meaning_vn:"sự đổi mới, cải tiến", definition_vn:"Giới thiệu ý tưởng, phương pháp hoặc sản phẩm mới.", definition_en:"Introduction of new ideas, methods, or products.", example:"Innovation drives economic growth.", level:"B2", source:"IELTS Core", topic:"Technology", difficulty:4, frequency_rank:2100, tags:["technology","business"], partOfSpeech:"noun" },

  // IELTS Core · B1–C1 · Education
  { word:"academic", meaning_vn:"học thuật", definition_vn:"Liên quan đến giáo dục và học thuật.", definition_en:"Relating to education and scholarship.", example:"Her academic performance improved significantly.", level:"B1", source:"IELTS Core", topic:"Education", difficulty:3, frequency_rank:1200, tags:["education"], partOfSpeech:"adjective" },
  { word:"curriculum", meaning_vn:"chương trình học", definition_vn:"Các môn học trong một trường hoặc chương trình.", definition_en:"The subjects taught in a school or course.", example:"The new curriculum includes coding lessons.", level:"B2", source:"IELTS Core", topic:"Education", difficulty:4, frequency_rank:2800, tags:["education","school"], partOfSpeech:"noun" },
  { word:"evaluate", meaning_vn:"đánh giá", definition_vn:"Xác định chất lượng hoặc giá trị của thứ gì đó.", definition_en:"To judge the quality or value of something.", example:"Students evaluate their own learning progress.", level:"B1", source:"IELTS Core", topic:"Education", difficulty:3, frequency_rank:1700, tags:["education"], partOfSpeech:"verb" },
  { word:"hypothesis", meaning_vn:"giả thuyết", definition_vn:"Một ý tưởng hoặc giải thích được đặt ra để kiểm chứng.", definition_en:"An idea or explanation that can be tested.", example:"The scientist proposed a new hypothesis.", level:"B2", source:"IELTS Core", topic:"Education", difficulty:4, frequency_rank:3200, tags:["education","science"], partOfSpeech:"noun" },
  { word:"scholarship", meaning_vn:"học bổng", definition_vn:"Tiền cấp để giúp học sinh trả tiền học.", definition_en:"Money given to help a student pay for education.", example:"She received a full scholarship to study abroad.", level:"B1", source:"IELTS Core", topic:"Education", difficulty:3, frequency_rank:2500, tags:["education"], partOfSpeech:"noun" },
  { word:"thesis", meaning_vn:"luận điểm, luận văn", definition_vn:"Một tuyên bố hoặc lý thuyết được đặt ra để tranh luận.", definition_en:"A statement or theory put forward as a premise.", example:"His thesis argued that technology improves education.", level:"B2", source:"IELTS Core", topic:"Education", difficulty:4, frequency_rank:3000, tags:["education","research"], partOfSpeech:"noun" },
  { word:"dissertation", meaning_vn:"luận văn", definition_vn:"Bài nghiên cứu dài được viết cho bằng đại học.", definition_en:"A long piece of writing done for a university degree.", example:"She spent a year writing her dissertation.", level:"C1", source:"IELTS Core", topic:"Education", difficulty:5, frequency_rank:4000, tags:["education","university"], partOfSpeech:"noun" },

  // TOEIC Core · B1–B2 · Business
  { word:"agenda", meaning_vn:"chương trình nghị sự", definition_vn:"Danh sách các mục sẽ thảo luận trong cuộc họp.", definition_en:"A list of items to be discussed at a meeting.", example:"Please review the meeting agenda beforehand.", level:"B1", source:"TOEIC Core", topic:"Business", difficulty:3, frequency_rank:2200, tags:["business","meetings"], partOfSpeech:"noun" },
  { word:"invoice", meaning_vn:"hóa đơn", definition_vn:"Danh sách hàng hóa hoặc dịch vụ kèm theo giá.", definition_en:"A list of goods or services provided with prices.", example:"Please send the invoice to our accounts department.", level:"B1", source:"TOEIC Core", topic:"Business", difficulty:3, frequency_rank:2700, tags:["business","finance"], partOfSpeech:"noun" },
  { word:"logistics", meaning_vn:"hậu cần", definition_vn:"Việc tổ chức và điều phối một hoạt động phức tạp.", definition_en:"The organization of a complex operation.", example:"Our logistics team ensures on-time delivery.", level:"B2", source:"TOEIC Core", topic:"Business", difficulty:4, frequency_rank:3000, tags:["business"], partOfSpeech:"noun" },
  { word:"merger", meaning_vn:"sự sáp nhập", definition_vn:"Sự kết hợp của hai công ty thành một.", definition_en:"The combination of two companies into one.", example:"The merger created the world's largest bank.", level:"B2", source:"TOEIC Core", topic:"Business", difficulty:4, frequency_rank:3400, tags:["business","corporate"], partOfSpeech:"noun" },
  { word:"presentation", meaning_vn:"thuyết trình", definition_vn:"Việc trình bày thông tin cho một nhóm người.", definition_en:"The act of showing information to a group.", example:"She gave an excellent presentation to the board.", level:"A2", source:"TOEIC Core", topic:"Business", difficulty:2, frequency_rank:1400, tags:["business","communication"], partOfSpeech:"noun" },
  { word:"delegate", meaning_vn:"ủy quyền, giao nhiệm vụ", definition_vn:"Giao công việc hoặc trách nhiệm cho người khác.", definition_en:"To give work or responsibility to someone else.", example:"A good manager knows how to delegate tasks.", level:"B2", source:"TOEIC Core", topic:"Business", difficulty:4, frequency_rank:2600, tags:["business","management"], partOfSpeech:"verb" },
  { word:"correspondence", meaning_vn:"thư từ, trao đổi thư từ", definition_vn:"Thư hoặc email trao đổi giữa các bên.", definition_en:"Letters or emails exchanged between parties.", example:"All business correspondence must be archived.", level:"B2", source:"TOEIC Core", topic:"Business", difficulty:4, frequency_rank:3100, tags:["business","communication"], partOfSpeech:"noun" },
];

module.exports = words;
